### ISSUE TITLE
Съехали пользовательские новеллы

### ISSUE THREAD

**Issue by shinkaxr** [mistersaal/novel#1]
![cVq_nmkFMd0](https://user-images.githubusercontent.com/41586023/100906716-88594a00-34da-11eb-9826-20896ba1766d.jpg)

**Comment by mistersaal** [comment]
![image](https://user-images.githubusercontent.com/50755371/101238415-27f02580-36f1-11eb-85ae-2d070f96d6e6.png)
Пофиксил перенос, также сделал уменьшение размера заголовка новеллы, если название длинное
