### ISSUE TITLE
Неправильная проверка содержания графы e-mail

### ISSUE THREAD

**Issue by shinkaxr** [mistersaal/novel#2]
![U-I9pmnX9Jo](https://user-images.githubusercontent.com/41586023/100906800-9b6c1a00-34da-11eb-863f-5c92a85de4c3.jpg)

**Comment by mistersaal** [comment]
Валидация основана на HTML5 <input type="email">, не вижу смысла делать дополнительную валидацию этого поля, учитывая, что это ничего не ломает
